### ISSUE TITLE
番剧地址输入硕鼠只能解析出第一集的m3u8链接

### ISSUE THREAD

**Issue by YFTX2015** [czzonet/acfun-video-downloader#1]

**Comment by czzonet** [comment]
更新了新方法，不需要用硕鼠了，你可以尝试下:)

**Comment by YFTX2015** [comment]
![屏幕截图(3)](https://user-images.githubusercontent.com/12757305/73858169-ec878f00-4872-11ea-94d5-84910379464b.png)

**Comment by czzonet** [comment]
已修复番剧无法提取的问题

**Comment by czzonet** [comment]
但好像也是只能解析当前页面的视频，都只能一集一集下载的

**Comment by YFTX2015** [comment]
![屏幕截图(1)](https://user-images.githubusercontent.com/12757305/74409015-ce242380-4e70-11ea-8c9f-6b3f97cf0230.png)
![屏幕截图(2)](https://user-images.githubusercontent.com/12757305/74409022-d0867d80-4e70-11ea-80eb-7150e23a2a4a.png)

**Comment by czzonet** [comment]
同一个视频效果：

<img width="960" alt="Snipaste_2020-02-14_14-06-41" src="https://user-images.githubusercontent.com/16220009/74505964-6c78bd80-4f33-11ea-8f66-ed7f750cb538.png">

**Comment by czzonet** [comment]
**此处操作有问题：**

<img width="327" alt="Snipaste_2020-02-14_14-16-50" src="https://user-images.githubusercontent.com/16220009/74506504-bd3ce600-4f34-11ea-881e-97ad008bfbfd.png">

**Comment by YFTX2015** [comment]
好了，测试成功
